---
language: bash

jobs:
  include:
    - name: Linux Test
      os: linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update && sudo apt-get install -y git; fi

script:
  - ./install
