---
name: Ubuntu Dotfiles Testing

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Execute install
        run: |
          ./install
